export const GET_LISTEN_SNIPPETS = "GET_LISTEN_SNIPPETS";
export const GET_LISTEN_SNIPPET = "GET_LISTEN_SNIPPET";
export const PUT_LISTEN_SNIPPET = "PUT_LISTEN_SNIPPET";


export const ADD_SPEAKER = "ADD_SPEAKER";


export const GET_RECORD_SNIPPETS = "GET_RECORD_SNIPPETS";
export const GET_RECORD_SNIPPET = "GET_RECORD_SNIPPET";
export const PUT_RECORD_SNIPPET = "PUT_RECORD_SNIPPET";


export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGES = "CREATE_MESSAGES"