# Generated by Django 2.2.14 on 2022-02-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicelines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='user',
        ),
        migrations.AddField(
            model_name='snippet',
            name='is_recorded',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='is_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='text',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='voicelines.NepaliText'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='verification_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
