# Generated by Django 2.2.14 on 2022-02-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicelines', '0002_auto_20220207_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepaliTextCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.FileField(blank=True, null=True, upload_to='text_files/')),
            ],
        ),
    ]
